### PR TITLE
Short C2M2 blurb

### PR DESCRIPTION
**Pull request by abhijna**
I've added the C2M2 blurb as a .md. Please edit as needed!

### CODE REVIEW

**Comment by ACharbonneau** [comment]
@kloydrti Here's the updated c2M2 info. Could you please make it so `## How does the model work?`, `## How do data coordinators participate? `, and `## What can a researcher use the model levels for?` are subpages of the top section instead of it being one very long page please

**Comment by kloydrti** [comment]
The levels roadmap document that was on the C2M2 landing page has been replaced with the first part of the new blurb. The 3 other headings are on their own pages and listed in the side menu, which now looks like this:
Screen Shot 2020-07-02 at 8 57 15 AM
Should any of the other sub-pages be taken down? Should the levels roadmap be giving its own page so it's still available?

**Comment by ACharbonneau** [comment]
All of the old pages for C2M2 should get taken down, they got moved to the 'technical documentation' site

**Comment by kloydrti** [comment]
OK, the other pages were taken down except the C2M2 glossary since it's referenced in the new pages. I also changed "Model Levels Usage" to "How To Use Model Levels" so it fits with the other two pages better.

**Pull request merged**
